### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Enkratia** [kitloong/json-server-vercel#9]
Hello,

In module usage everything is working perfect, but /register  - does not register new users, it says - you must add "users" (but "users" already exist). Paradox: at the same time /register knows that your email was registered, by checking it in "users" and it sends message : "email already exist".

*User registered earlier localy.

```
const jsonServer = require("json-server");
const auth = require("json-server-auth");

const server = jsonServer.create();
const router = jsonServer.router("db.json");
const middlewares = jsonServer.defaults();

server.db = router.db;

// Add this before server.use(router)
server.use(middlewares);
server.use(auth);

server.use(router);
server.listen(3000, () => {
  console.log("JSON Server is running");
});

// Export the Server API
module.exports = server;
```

**Comment by whoafridi** [comment]
waiting for fixing  ..

**Comment by kitloong** [comment]
Hi @Enkratia , I am sorry for the dealy.

Please follow https://github.com/kitloong/json-server-vercel/issues/6#issuecomment-1643159128 to enable write operations.

**Comment by Enkratia** [comment]
Thanks to you and @VicAv99. Now it works.
